### ISSUE TITLE
Nur am Wochen Tag möglich?

### ISSUE THREAD

**Issue by vr6syncro** [ioBroker/ioBroker.fullcalendar#1]
Ist es möglich die Funktion nur am Wochentag mit einzufügen? oder nur am Wochenende? Das man da etwas flexibler ist.

Period: MO-FR oder per Kästchen anklickbar MO,DI,FR / Einmalig / Wiederholend

**Comment by GermanBluefox** [comment]
Man kann an beliebigen Tagen das einstellen:
![image](https://user-images.githubusercontent.com/4582016/33153644-55032414-cfe3-11e7-81d0-033ce9e10693.png)
