### ISSUE TITLE
andere Wochenrythmen ermöglichen (Feature Request)

### ISSUE THREAD

**Issue by grimneko** [ioBroker/ioBroker.fullcalendar#2]
Was ich mir wünschen würde für diese ioBroker Plugin ist die Möglichkeit einen Termin zb alle 5 Wochen eintragen zu können. Zb wenn ich wöchentlich anwähle, möchte ich auswählen können alle wieviel Wochen. Damit kann man unregelmäßige Systeme wie Schichten gut abbilden.

**Comment by Issr4k** [comment]
FInde ich ebenfalls gut!

**Comment by soundylinz** [comment]
Auch interessant wäre sowas wie: 

- Alle x Tage
- Alle x Wochen
- Alle x Monate
