### ISSUE TITLE
can't use instanz

### ISSUE THREAD

**Issue by Pipel19** [ioBroker/ioBroker.fullcalendar#319]
**Describe the bug**  
One instanz is running on my system. If I want to open the calender in the nothing happened, only wide screen.

**To Reproduce**  
1. Instanz is running. 
2. Click on the left side on the calender icon
3. Side is loading, empty page (see screenshot)
4. In log file is a disconnect message

**Expected behavior**  
the calender shout start and I can set it up

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.
```
<html>
<body>
<!--StartFragment-->
admin.0 | 72128 | 2024-09-08 21:28:59.942 | info | <== Disconnect system.user.admin from ::ffff:192.168.2.120 fullcalendar
admin.0 | 72128 | 2024-09-08 21:28:59.942 | info | <== Disconnect system.user.admin from ::ffff:192.168.2.120 fullcalendar
admin.0 | 72128 | 2024-09-08 21:28:52.612 | info | ==> Connected system.user.admin from ::ffff:192.168.2.120

<!--EndFragment-->
</body>
</html>
``` 
<img width="1400" alt="image" src="https://github.com/user-attachments/assets/dafceea4-f3f0-49d7-b294-911810c590c5">

**Versions:**  
 - Adapter version: 2.4.2
 - JS-Controller version: 6.0.11
 - Node version: v18.20.3
 - Operating system: Raspberry Pi OS (64-bit)

**Comment by skipperkm** [comment]
Hi,

das gleiche Problem, Kalender arbeitet, läßt sich aber nicht mehr konfigurieren. Leere Seite bei Aufruf über die Menüleiste.

CPU: 0,13 %
RAM: 57 %
Betriebszeit: 4d15h
Verfügbar: 6.0.11
Installiert: 6.0.11
Ereignisse: ⇥43 / ↦13
Plattform: linux
Betriebssystem: linux
Architektur: x64
CPUs: 2
Geschwindigkeit: 0 MHz
Modell: QEMU Virtual CPU version 2.5+
RAM: 11.6 GB
System-Betriebszeit: 4 T. 15:44:55
Node.js: v20.17.0
time: 1725866744132
timeOffset: -120
NPM: 10.8.2
Adapter-Anzahl: 540
Datenträgergröße: 59.9 GB
Freier Festplattenspeicher: 14.5 GB
Aktive Instanzen: 43
Pfad: /opt/iobroker/
Betriebszeit: 4 T. 15:44:34
aktiv: true
_nodeCurrent: 20.17.0
_nodeNewestNext: 20.17.0
_npmCurrent: 10.8.2
_nodeNewest: 20.17.0
_npmNewest: 10.8.2
_npmNewestNext: 10.8.2
