### ISSUE TITLE
Timezone problem

### ISSUE THREAD

**Issue by bornatowicz** [ioBroker/ioBroker.fullcalendar#36]
**Describe the bug**  
I live in Vienna. All events are 1 hour to late. How can i fix this?

**Versions:**  
 - Adapter version: 1.2.0
 - JS-Controller version: V14.19.0
 - Node version: 4.0.15
 - Operating system: Proxmox CT

**Additional context**  
Change  timezone: 'Europe/Berlin' in tab.html wasn't fix this

**Comment by Apollon77** [comment]
Please check the time of your iobroker host ... and fix the time there
