### ISSUE TITLE
Bool auf true setzen

### ISSUE THREAD

**Issue by Minninnewah** [ioBroker/ioBroker.fullcalendar#7]
Gueten Abend

Ich hoffe, dass ich hier richtig bin.
Wenn ich im fullcalender ein Javascriptvariabel auf true setze, wird diese bei der Abfrage in einer Onchange funktion nicht als true erkannt. Wenn ich nun aber im Adminbereich unter objekte diesen Wert nochmals auswähle und Enter drücke funktioniert es wieder.

Mach ich da einen Fehler beim Setzen oder ist das noch ein Bug? (Ich hoffe es ist mein Fehler)

**Comment by Apollon77** [comment]
Als was wird der Wert denn erkannt bzw was genau ist denn der Wert?

**Comment by Minninnewah** [comment]
Dachte sei immer ein Bool gewesen, hab es jetzt aber nochmals schnell angeschaut....Ist ein String --> Code auch auf String angepasst und funktioniert wieder. Danke für den Anschubser und sry für die Störung xD.

Wenn ich gad schon dabei bin, gibt es eine Möglichkeit aus dem fullcalender einen bool zu setzen?
![fiullcalendar_1](https://user-images.githubusercontent.com/40040609/41146889-26a8f1e4-6b05-11e8-81eb-c9852e981e49.PNG)

**Comment by Apollon77** [comment]
Wenn das zus etzende State ein Boolean ist sollte er es korrekt setzen

**Comment by Minninnewah** [comment]
Es ist als Logikwert vestgelegt:
![fiullcalendar_3](https://user-images.githubusercontent.com/40040609/41155015-7f85c92e-6b1c-11e8-8816-d40ef4c8fab2.PNG)

**Comment by GermanBluefox** [comment]
Diese Zeile sollte dann die Arbeit machen:
https://github.com/ioBroker/ioBroker.fullcalendar/blob/master/main.js#L205

Wenn du immer noch das Problem hast, dass die Werte als String gesetzt werden kannst du dann hier:
https://github.com/ioBroker/ioBroker.fullcalendar/blob/master/main.js#L212
so was hinzufügen:
```
   adpater.log.warn('event.native.startValue = ' + event.native.startValue + ' ' + typeof event.native.startValue);
```
Und hier posten?

**Comment by GermanBluefox** [comment]
adpater => adapter

сб, 9 июн. 2018 г., 10:24 Minninnewah <notifications@github.com>:

**Comment by Minninnewah** [comment]
Endlich komme ich wieder dazu...

![fullcalender_log_1](https://user-images.githubusercontent.com/40040609/41523541-ab1885de-72da-11e8-899c-b3684a74c02e.PNG)

Hilft das weiter? Anscheinend ist es immer noch ein String der zurückgegeben wird.
